//! Port of `silk/define.h`: SILK compile-time constants.
#![allow(
    missing_docs,
    reason = "constants mirror the C header one-to-one; see the C source for meaning"
)]
/// `ENCODER_NUM_CHANNELS`
pub const ENCODER_NUM_CHANNELS: i32 = 2;
/// `DECODER_NUM_CHANNELS`
pub const DECODER_NUM_CHANNELS: i32 = 2;
/// `MAX_FRAMES_PER_PACKET`
pub const MAX_FRAMES_PER_PACKET: i32 = 3;
/// `MIN_TARGET_RATE_BPS`
pub const MIN_TARGET_RATE_BPS: i32 = 5000;
/// `MAX_TARGET_RATE_BPS`
pub const MAX_TARGET_RATE_BPS: i32 = 80000;
/// `LBRR_NB_MIN_RATE_BPS`
pub const LBRR_NB_MIN_RATE_BPS: i32 = 12000;
/// `LBRR_MB_MIN_RATE_BPS`
pub const LBRR_MB_MIN_RATE_BPS: i32 = 14000;
/// `LBRR_WB_MIN_RATE_BPS`
pub const LBRR_WB_MIN_RATE_BPS: i32 = 16000;
/// `NB_SPEECH_FRAMES_BEFORE_DTX` — eq 200 ms
pub const NB_SPEECH_FRAMES_BEFORE_DTX: i32 = 10;
/// `MAX_CONSECUTIVE_DTX` — eq 400 ms
pub const MAX_CONSECUTIVE_DTX: i32 = 20;
/// `DTX_ACTIVITY_THRESHOLD`
pub const DTX_ACTIVITY_THRESHOLD: f32 = 0.1;
/// `VAD_NO_DECISION`
pub const VAD_NO_DECISION: i32 = -1;
/// `VAD_NO_ACTIVITY`
pub const VAD_NO_ACTIVITY: i32 = 0;
/// `VAD_ACTIVITY`
pub const VAD_ACTIVITY: i32 = 1;
/// `MAX_FS_KHZ`
pub const MAX_FS_KHZ: i32 = 16;
/// `MAX_API_FS_KHZ`
#[cfg(feature = "qext")]
pub const MAX_API_FS_KHZ: i32 = 96;
/// `MAX_API_FS_KHZ`
#[cfg(not(feature = "qext"))]
pub const MAX_API_FS_KHZ: i32 = 48;
/// `TYPE_NO_VOICE_ACTIVITY`
pub const TYPE_NO_VOICE_ACTIVITY: i32 = 0;
/// `TYPE_UNVOICED`
pub const TYPE_UNVOICED: i32 = 1;
/// `TYPE_VOICED`
pub const TYPE_VOICED: i32 = 2;
/// `CODE_INDEPENDENTLY`
pub const CODE_INDEPENDENTLY: i32 = 0;
/// `CODE_INDEPENDENTLY_NO_LTP_SCALING`
pub const CODE_INDEPENDENTLY_NO_LTP_SCALING: i32 = 1;
/// `CODE_CONDITIONALLY`
pub const CODE_CONDITIONALLY: i32 = 2;
/// `STEREO_QUANT_TAB_SIZE`
pub const STEREO_QUANT_TAB_SIZE: i32 = 16;
/// `STEREO_QUANT_SUB_STEPS`
pub const STEREO_QUANT_SUB_STEPS: i32 = 5;
/// `STEREO_INTERP_LEN_MS` — must be even
pub const STEREO_INTERP_LEN_MS: i32 = 8;
/// `STEREO_RATIO_SMOOTH_COEF` — smoothing coef for signal norms and stereo width
pub const STEREO_RATIO_SMOOTH_COEF: f64 = 0.01;
/// `PITCH_EST_MIN_LAG_MS` — 2 ms -> 500 Hz
pub const PITCH_EST_MIN_LAG_MS: i32 = 2;
/// `PITCH_EST_MAX_LAG_MS` — 18 ms -> 56 Hz
pub const PITCH_EST_MAX_LAG_MS: i32 = 18;
/// `MAX_NB_SUBFR`
pub const MAX_NB_SUBFR: i32 = 4;
/// `LTP_MEM_LENGTH_MS`
pub const LTP_MEM_LENGTH_MS: i32 = 20;
/// `SUB_FRAME_LENGTH_MS`
pub const SUB_FRAME_LENGTH_MS: i32 = 5;
/// `MAX_SUB_FRAME_LENGTH`
pub const MAX_SUB_FRAME_LENGTH: i32 = SUB_FRAME_LENGTH_MS * MAX_FS_KHZ;
/// `MAX_FRAME_LENGTH_MS`
pub const MAX_FRAME_LENGTH_MS: i32 = SUB_FRAME_LENGTH_MS * MAX_NB_SUBFR;
/// `MAX_FRAME_LENGTH`
pub const MAX_FRAME_LENGTH: i32 = MAX_FRAME_LENGTH_MS * MAX_FS_KHZ;
/// `LA_PITCH_MS`
pub const LA_PITCH_MS: i32 = 2;
/// `LA_PITCH_MAX`
pub const LA_PITCH_MAX: i32 = LA_PITCH_MS * MAX_FS_KHZ;
/// `MAX_FIND_PITCH_LPC_ORDER`
pub const MAX_FIND_PITCH_LPC_ORDER: i32 = 16;
/// `FIND_PITCH_LPC_WIN_MS`
pub const FIND_PITCH_LPC_WIN_MS: i32 = 20 + (LA_PITCH_MS << 1);
/// `FIND_PITCH_LPC_WIN_MS_2_SF`
pub const FIND_PITCH_LPC_WIN_MS_2_SF: i32 = 10 + (LA_PITCH_MS << 1);
/// `FIND_PITCH_LPC_WIN_MAX`
pub const FIND_PITCH_LPC_WIN_MAX: i32 = FIND_PITCH_LPC_WIN_MS * MAX_FS_KHZ;
/// `LA_SHAPE_MS`
pub const LA_SHAPE_MS: i32 = 5;
/// `LA_SHAPE_MAX`
pub const LA_SHAPE_MAX: i32 = LA_SHAPE_MS * MAX_FS_KHZ;
/// `SHAPE_LPC_WIN_MAX`
pub const SHAPE_LPC_WIN_MAX: i32 = 15 * MAX_FS_KHZ;
/// `MIN_QGAIN_DB`
pub const MIN_QGAIN_DB: i32 = 2;
/// `MAX_QGAIN_DB`
pub const MAX_QGAIN_DB: i32 = 88;
/// `N_LEVELS_QGAIN`
pub const N_LEVELS_QGAIN: i32 = 64;
/// `MAX_DELTA_GAIN_QUANT`
pub const MAX_DELTA_GAIN_QUANT: i32 = 36;
/// `MIN_DELTA_GAIN_QUANT`
pub const MIN_DELTA_GAIN_QUANT: i32 = -4;
/// `OFFSET_VL_Q10`
pub const OFFSET_VL_Q10: i32 = 32;
/// `OFFSET_VH_Q10`
pub const OFFSET_VH_Q10: i32 = 100;
/// `OFFSET_UVL_Q10`
pub const OFFSET_UVL_Q10: i32 = 100;
/// `OFFSET_UVH_Q10`
pub const OFFSET_UVH_Q10: i32 = 240;
/// `QUANT_LEVEL_ADJUST_Q10`
pub const QUANT_LEVEL_ADJUST_Q10: i32 = 80;
/// `MAX_LPC_STABILIZE_ITERATIONS`
pub const MAX_LPC_STABILIZE_ITERATIONS: i32 = 16;
/// `MAX_PREDICTION_POWER_GAIN`
pub const MAX_PREDICTION_POWER_GAIN: f32 = 1e4;
/// `MAX_PREDICTION_POWER_GAIN_AFTER_RESET`
pub const MAX_PREDICTION_POWER_GAIN_AFTER_RESET: f32 = 1e2;
/// `MAX_LPC_ORDER`
pub const MAX_LPC_ORDER: i32 = 16;
/// `MIN_LPC_ORDER`
pub const MIN_LPC_ORDER: i32 = 10;
/// `LTP_ORDER`
pub const LTP_ORDER: i32 = 5;
/// `NB_LTP_CBKS`
pub const NB_LTP_CBKS: i32 = 3;
/// `USE_HARM_SHAPING`
pub const USE_HARM_SHAPING: i32 = 1;
/// `MAX_SHAPE_LPC_ORDER`
pub const MAX_SHAPE_LPC_ORDER: i32 = 24;
/// `HARM_SHAPE_FIR_TAPS`
pub const HARM_SHAPE_FIR_TAPS: i32 = 3;
/// `MAX_DEL_DEC_STATES`
pub const MAX_DEL_DEC_STATES: i32 = 4;
/// `LTP_BUF_LENGTH`
pub const LTP_BUF_LENGTH: i32 = 512;
/// `LTP_MASK`
pub const LTP_MASK: i32 = LTP_BUF_LENGTH - 1;
/// `DECISION_DELAY`
pub const DECISION_DELAY: i32 = 40;
/// `SHELL_CODEC_FRAME_LENGTH`
pub const SHELL_CODEC_FRAME_LENGTH: i32 = 16;
/// `LOG2_SHELL_CODEC_FRAME_LENGTH`
pub const LOG2_SHELL_CODEC_FRAME_LENGTH: i32 = 4;
/// `MAX_NB_SHELL_BLOCKS`
pub const MAX_NB_SHELL_BLOCKS: i32 = MAX_FRAME_LENGTH / SHELL_CODEC_FRAME_LENGTH;
/// `N_RATE_LEVELS`
pub const N_RATE_LEVELS: i32 = 10;
/// `SILK_MAX_PULSES`
pub const SILK_MAX_PULSES: i32 = 16;
/// `MAX_MATRIX_SIZE` — Max of LPC Order and LTP order
pub const MAX_MATRIX_SIZE: i32 = MAX_LPC_ORDER;
/// `NSQ_LPC_BUF_LENGTH`
pub const NSQ_LPC_BUF_LENGTH: i32 = MAX_LPC_ORDER;
/// `VAD_N_BANDS`
pub const VAD_N_BANDS: i32 = 4;
/// `VAD_INTERNAL_SUBFRAMES_LOG2`
pub const VAD_INTERNAL_SUBFRAMES_LOG2: i32 = 2;
/// `VAD_INTERNAL_SUBFRAMES`
pub const VAD_INTERNAL_SUBFRAMES: i32 = 1 << VAD_INTERNAL_SUBFRAMES_LOG2;
/// `VAD_NOISE_LEVEL_SMOOTH_COEF_Q16` — Must be <  4096
pub const VAD_NOISE_LEVEL_SMOOTH_COEF_Q16: i32 = 1024;
/// `VAD_NOISE_LEVELS_BIAS`
pub const VAD_NOISE_LEVELS_BIAS: i32 = 50;
/// `VAD_NEGATIVE_OFFSET_Q5` — sigmoid is 0 at -128
pub const VAD_NEGATIVE_OFFSET_Q5: i32 = 128;
/// `VAD_SNR_FACTOR_Q16`
pub const VAD_SNR_FACTOR_Q16: i32 = 45000;
/// `VAD_SNR_SMOOTH_COEF_Q18`
pub const VAD_SNR_SMOOTH_COEF_Q18: i32 = 4096;
/// `LSF_COS_TAB_SZ_FIX`
pub const LSF_COS_TAB_SZ_FIX: i32 = 128;
/// `NLSF_W_Q`
pub const NLSF_W_Q: i32 = 2;
/// `NLSF_VQ_MAX_VECTORS`
pub const NLSF_VQ_MAX_VECTORS: i32 = 32;
/// `NLSF_QUANT_MAX_AMPLITUDE`
pub const NLSF_QUANT_MAX_AMPLITUDE: i32 = 4;
/// `NLSF_QUANT_MAX_AMPLITUDE_EXT`
pub const NLSF_QUANT_MAX_AMPLITUDE_EXT: i32 = 10;
/// `NLSF_QUANT_LEVEL_ADJ`
pub const NLSF_QUANT_LEVEL_ADJ: f64 = 0.1;
/// `NLSF_QUANT_DEL_DEC_STATES_LOG2`
pub const NLSF_QUANT_DEL_DEC_STATES_LOG2: i32 = 2;
/// `NLSF_QUANT_DEL_DEC_STATES`
pub const NLSF_QUANT_DEL_DEC_STATES: i32 = 1 << NLSF_QUANT_DEL_DEC_STATES_LOG2;
/// `TRANSITION_TIME_MS` — 5120 = 64 * FRAME_LENGTH_MS * ( TRANSITION_INT_NUM - 1 ) = 64*(20*4)
pub const TRANSITION_TIME_MS: i32 = 5120;
/// `TRANSITION_NB` — Hardcoded in tables
pub const TRANSITION_NB: i32 = 3;
/// `TRANSITION_NA` — Hardcoded in tables
pub const TRANSITION_NA: i32 = 2;
/// `TRANSITION_INT_NUM` — Hardcoded in tables
pub const TRANSITION_INT_NUM: i32 = 5;
/// `TRANSITION_FRAMES`
pub const TRANSITION_FRAMES: i32 = TRANSITION_TIME_MS / MAX_FRAME_LENGTH_MS;
/// `TRANSITION_INT_STEPS`
pub const TRANSITION_INT_STEPS: i32 = TRANSITION_FRAMES / (TRANSITION_INT_NUM - 1);
/// `BWE_AFTER_LOSS_Q16`
pub const BWE_AFTER_LOSS_Q16: i32 = 63570;
/// `CNG_BUF_MASK_MAX` — 2^floor(log2(MAX_FRAME_LENGTH))-1
pub const CNG_BUF_MASK_MAX: i32 = 255;
/// `CNG_GAIN_SMTH_Q16` — 0.25^(1/4)
pub const CNG_GAIN_SMTH_Q16: i32 = 4634;
/// `CNG_GAIN_SMTH_THRESHOLD_Q16` — -3 dB
pub const CNG_GAIN_SMTH_THRESHOLD_Q16: i32 = 46396;
/// `CNG_NLSF_SMTH_Q16` — 0.25
pub const CNG_NLSF_SMTH_Q16: i32 = 16348;
