//! Port of `silk/errors.h`: SILK error codes.
#![allow(
    missing_docs,
    reason = "constants mirror the C header one-to-one; see the C source for meaning"
)]
/// `SILK_NO_ERROR`
pub const SILK_NO_ERROR: i32 = 0;
/// `SILK_ENC_INPUT_INVALID_NO_OF_SAMPLES`
pub const SILK_ENC_INPUT_INVALID_NO_OF_SAMPLES: i32 = -101;
/// `SILK_ENC_FS_NOT_SUPPORTED`
pub const SILK_ENC_FS_NOT_SUPPORTED: i32 = -102;
/// `SILK_ENC_PACKET_SIZE_NOT_SUPPORTED`
pub const SILK_ENC_PACKET_SIZE_NOT_SUPPORTED: i32 = -103;
/// `SILK_ENC_PAYLOAD_BUF_TOO_SHORT`
pub const SILK_ENC_PAYLOAD_BUF_TOO_SHORT: i32 = -104;
/// `SILK_ENC_INVALID_LOSS_RATE`
pub const SILK_ENC_INVALID_LOSS_RATE: i32 = -105;
/// `SILK_ENC_INVALID_COMPLEXITY_SETTING`
pub const SILK_ENC_INVALID_COMPLEXITY_SETTING: i32 = -106;
/// `SILK_ENC_INVALID_INBAND_FEC_SETTING`
pub const SILK_ENC_INVALID_INBAND_FEC_SETTING: i32 = -107;
/// `SILK_ENC_INVALID_DTX_SETTING`
pub const SILK_ENC_INVALID_DTX_SETTING: i32 = -108;
/// `SILK_ENC_INVALID_CBR_SETTING`
pub const SILK_ENC_INVALID_CBR_SETTING: i32 = -109;
/// `SILK_ENC_INTERNAL_ERROR`
pub const SILK_ENC_INTERNAL_ERROR: i32 = -110;
/// `SILK_ENC_INVALID_NUMBER_OF_CHANNELS_ERROR`
pub const SILK_ENC_INVALID_NUMBER_OF_CHANNELS_ERROR: i32 = -111;
/// `SILK_DEC_INVALID_SAMPLING_FREQUENCY`
pub const SILK_DEC_INVALID_SAMPLING_FREQUENCY: i32 = -200;
/// `SILK_DEC_PAYLOAD_TOO_LARGE`
pub const SILK_DEC_PAYLOAD_TOO_LARGE: i32 = -201;
/// `SILK_DEC_PAYLOAD_ERROR`
pub const SILK_DEC_PAYLOAD_ERROR: i32 = -202;
/// `SILK_DEC_INVALID_FRAME_SIZE`
pub const SILK_DEC_INVALID_FRAME_SIZE: i32 = -203;
