//! Port of `silk/tuning_parameters.h`: SILK encoder tuning parameters.
#![allow(
    non_upper_case_globals,
    missing_docs,
    reason = "constants mirror the C header one-to-one; see the C source for meaning"
)]
/// `BITRESERVOIR_DECAY_TIME_MS`
pub const BITRESERVOIR_DECAY_TIME_MS: i32 = 500;
/// `FIND_PITCH_WHITE_NOISE_FRACTION`
pub const FIND_PITCH_WHITE_NOISE_FRACTION: f32 = 1e-3;
/// `FIND_PITCH_BANDWIDTH_EXPANSION`
pub const FIND_PITCH_BANDWIDTH_EXPANSION: f32 = 0.99;
/// `FIND_LPC_COND_FAC`
pub const FIND_LPC_COND_FAC: f32 = 1e-5;
/// `MAX_SUM_LOG_GAIN_DB`
pub const MAX_SUM_LOG_GAIN_DB: f32 = 250.0;
/// `LTP_CORR_INV_MAX`
pub const LTP_CORR_INV_MAX: f32 = 0.03;
/// `VARIABLE_HP_SMTH_COEF1`
pub const VARIABLE_HP_SMTH_COEF1: f32 = 0.1;
/// `VARIABLE_HP_SMTH_COEF2`
pub const VARIABLE_HP_SMTH_COEF2: f32 = 0.015;
/// `VARIABLE_HP_MAX_DELTA_FREQ`
pub const VARIABLE_HP_MAX_DELTA_FREQ: f32 = 0.4;
/// `VARIABLE_HP_MIN_CUTOFF_HZ`
pub const VARIABLE_HP_MIN_CUTOFF_HZ: i32 = 60;
/// `VARIABLE_HP_MAX_CUTOFF_HZ`
pub const VARIABLE_HP_MAX_CUTOFF_HZ: i32 = 100;
/// `SPEECH_ACTIVITY_DTX_THRES`
pub const SPEECH_ACTIVITY_DTX_THRES: f32 = 0.05;
/// `LBRR_SPEECH_ACTIVITY_THRES`
pub const LBRR_SPEECH_ACTIVITY_THRES: f32 = 0.3;
/// `BG_SNR_DECR_dB`
pub const BG_SNR_DECR_dB: f32 = 2.0;
/// `HARM_SNR_INCR_dB`
pub const HARM_SNR_INCR_dB: f32 = 2.0;
/// `SPARSE_SNR_INCR_dB`
pub const SPARSE_SNR_INCR_dB: f32 = 2.0;
/// `ENERGY_VARIATION_THRESHOLD_QNT_OFFSET`
pub const ENERGY_VARIATION_THRESHOLD_QNT_OFFSET: f32 = 0.6;
/// `WARPING_MULTIPLIER`
pub const WARPING_MULTIPLIER: f32 = 0.015;
/// `SHAPE_WHITE_NOISE_FRACTION`
pub const SHAPE_WHITE_NOISE_FRACTION: f32 = 3e-5;
/// `BANDWIDTH_EXPANSION`
pub const BANDWIDTH_EXPANSION: f32 = 0.94;
/// `HARMONIC_SHAPING`
pub const HARMONIC_SHAPING: f32 = 0.3;
/// `HIGH_RATE_OR_LOW_QUALITY_HARMONIC_SHAPING`
pub const HIGH_RATE_OR_LOW_QUALITY_HARMONIC_SHAPING: f32 = 0.2;
/// `HP_NOISE_COEF`
pub const HP_NOISE_COEF: f32 = 0.25;
/// `HARM_HP_NOISE_COEF`
pub const HARM_HP_NOISE_COEF: f32 = 0.35;
/// `INPUT_TILT`
pub const INPUT_TILT: f32 = 0.05;
/// `HIGH_RATE_INPUT_TILT`
pub const HIGH_RATE_INPUT_TILT: f32 = 0.1;
/// `LOW_FREQ_SHAPING`
pub const LOW_FREQ_SHAPING: f32 = 4.0;
/// `LOW_QUALITY_LOW_FREQ_SHAPING_DECR`
pub const LOW_QUALITY_LOW_FREQ_SHAPING_DECR: f32 = 0.5;
/// `SUBFR_SMTH_COEF`
pub const SUBFR_SMTH_COEF: f32 = 0.4;
/// `LAMBDA_OFFSET`
pub const LAMBDA_OFFSET: f32 = 1.2;
/// `LAMBDA_SPEECH_ACT`
pub const LAMBDA_SPEECH_ACT: f32 = -0.2;
/// `LAMBDA_DELAYED_DECISIONS`
pub const LAMBDA_DELAYED_DECISIONS: f32 = -0.05;
/// `LAMBDA_INPUT_QUALITY`
pub const LAMBDA_INPUT_QUALITY: f32 = -0.1;
/// `LAMBDA_CODING_QUALITY`
pub const LAMBDA_CODING_QUALITY: f32 = -0.2;
/// `LAMBDA_QUANT_OFFSET`
pub const LAMBDA_QUANT_OFFSET: f32 = 0.8;
/// `REDUCE_BITRATE_10_MS_BPS`
pub const REDUCE_BITRATE_10_MS_BPS: i32 = 2200;
/// `MAX_BANDWIDTH_SWITCH_DELAY_MS`
pub const MAX_BANDWIDTH_SWITCH_DELAY_MS: i32 = 5000;
