//! Differential tests for unit `celt_decoder` (celt/celt_decoder.c): the CELT decoder vs the C
//! oracle, bit-exact on PCM output, return codes, final range and the complete decoder state
//! after every call, on long packet streams generated by the C CELT encoder (all frame sizes,
//! mono/stereo and channel conversions, CBR/VBR from tiny to maximal budgets, transient and
//! tonal signals with the post-filter, intensity/dual stereo, hybrid start band 17 on a shared
//! range decoder, end band limits, 48/24/16/12/8 kHz output, packet loss (noise and pitch PLC),
//! corrupted packets, accumulation, resets), plus direct tests of the static helpers
//! (`tf_decode`, `deemphasis`, `celt_synthesis`, `celt_plc_pitch_search`) and the CTLs. QEXT
//! (96 kHz and 48 kHz extension payloads) and custom modes (`opus_custom_decode*`) run with
//! their features.
//!
//! Shared by the float and the fixed-point builds (`fixed-point`, `fixed-res24`, with or
//! without `qext` / `custom-modes`): the C encoder of the matching oracle produces the packets
//! (float test signals converted with `FLOAT2RES`), the helper inputs are generated as float
//! values and converted to the build's types, and every comparison (PCM as `opus_res`, final
//! range, complete decoder state) is bit-exact.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::too_many_arguments,
    clippy::excessive_precision,
    reason = "test code: failures should panic"
)]

use opusorus::celt::arch::{CeltGlog, CeltNorm, CeltSig, OpusVal16};
use opusorus::celt::celt_decoder::*;
use opusorus::celt::entdec::EcDec;
use opusorus::celt::modes::opus_custom_mode_create;
use opusorus::celt::static_modes::CeltMode;
#[cfg(all(feature = "custom-modes", not(feature = "disable-float-api")))]
use opusorus_conformance::assert_bits_eq_f32;
use opusorus_conformance::{Rng, assert_slice_eq, signals};
use opusorus_oracle::celt_decoder::{self as c, CeltDecState, CeltEnc, Res, StateVal};
use opusorus_oracle::sys;

// ---------------------------------------------------------------------------------------------
// Build-generic values
// ---------------------------------------------------------------------------------------------

/// Bit pattern of a value, for bit-exact comparisons of float and integer data alike.
trait Bits: Copy + core::fmt::Debug {
    fn bits(self) -> u64;
}
impl Bits for f32 {
    fn bits(self) -> u64 {
        u64::from(self.to_bits())
    }
}
impl Bits for i32 {
    fn bits(self) -> u64 {
        u64::from(self as u32)
    }
}
impl Bits for i16 {
    fn bits(self) -> u64 {
        u64::from(self as u16)
    }
}

/// Asserts that two slices are bit-identical.
#[track_caller]
fn assert_v<T: Bits>(what: &str, rust: &[T], c: &[T]) {
    assert_eq!(rust.len(), c.len(), "{what}: length mismatch");
    if let Some(i) = rust.iter().zip(c).position(|(a, b)| a.bits() != b.bits()) {
        panic!(
            "{what}: first mismatch at {i}: rust={:?} c={:?}",
            rust[i], c[i]
        );
    }
}

/// Scales `x` by `2^q` with rounding and saturation to `[-lim, lim]` (fixed-point inputs).
#[cfg(feature = "fixed-point")]
fn fx(x: f32, q: i32, lim: i64) -> i64 {
    ((f64::from(x) * (1i64 << q) as f64).round() as i64).clamp(-lim, lim)
}

/// An `opus_res` from a float sample in [-1, 1] (`FLOAT2RES`-like; the float build keeps it).
#[cfg(not(feature = "fixed-point"))]
const fn res(x: f32) -> Res {
    x
}
#[cfg(feature = "fixed-res24")]
fn res(x: f32) -> Res {
    fx(x, 23, (1 << 23) - 1) as i32
}
#[cfg(all(feature = "fixed-point", not(feature = "fixed-res24")))]
fn res(x: f32) -> Res {
    fx(x, 15, 32767) as i16
}
/// A `celt_sig` from a value in 16-bit PCM units (`SIG_SHIFT` above them in the fixed-point
/// build, saturated to `SIG_SAT` like the decoder's signals).
#[cfg(not(feature = "fixed-point"))]
const fn sig(x: f32) -> CeltSig {
    x
}
#[cfg(feature = "fixed-point")]
fn sig(x: f32) -> CeltSig {
    fx(x, 12, 536_870_911) as i32
}
/// A `celt_norm` from a float value (Q24 in the fixed-point build).
#[cfg(not(feature = "fixed-point"))]
const fn nrm(x: f32) -> CeltNorm {
    x
}
#[cfg(feature = "fixed-point")]
fn nrm(x: f32) -> CeltNorm {
    fx(x, 24, 1 << 30) as i32
}
/// A `celt_glog` from a value in log2 units (Q24 in the fixed-point build).
#[cfg(not(feature = "fixed-point"))]
const fn glog(x: f32) -> CeltGlog {
    x
}
#[cfg(feature = "fixed-point")]
fn glog(x: f32) -> CeltGlog {
    fx(x, 24, 1 << 30) as i32
}
/// A `Vec` of `n` build-typed values made by `f` from `rng`.
fn gen_vals<T>(n: usize, rng: &mut Rng, mut f: impl FnMut(&mut Rng) -> T) -> Vec<T> {
    (0..n).map(|_| f(rng)).collect()
}

/// Amplitude of the random normalised spectrum of the `celt_synthesis` tests.
const XAMP: f32 = 1.0;
/// Amplitude of the random band energies (log2 units) of the `celt_synthesis` tests.
const EAMP: f32 = 12.0;

/// Amplitude of the random de-emphasis memories for input amplitude `amp`: the fixed-point
/// decoder's memory is `coef0*SATURATE(x+mem)`, well below `SIG_SAT`, so `x + mem` cannot
/// overflow (100000 PCM units).
#[cfg(feature = "fixed-point")]
const fn mem_amp(amp: f32) -> f32 {
    amp.min(100_000.0)
}
#[cfg(not(feature = "fixed-point"))]
const fn mem_amp(amp: f32) -> f32 {
    amp
}

// CELT encoder requests (celt/celt.h).
const CELT_SET_PREDICTION_REQUEST: i32 = 10002;

// ---------------------------------------------------------------------------------------------
// Rust state dump (same layout as oracle_cd_state in csrc/celt_decoder.c)
// ---------------------------------------------------------------------------------------------

fn rust_state(d: &CeltDecoder<'_>) -> CeltDecState {
    #[cfg(feature = "qext")]
    let qext_scale = d.qext_scale;
    #[cfg(not(feature = "qext"))]
    let qext_scale = 1;
    let ints = [
        d.overlap,
        d.channels,
        d.stream_channels,
        d.downsample,
        d.start,
        d.end,
        d.signalling,
        d.disable_inv,
        d.complexity,
        qext_scale,
        d.rng as i32,
        d.error,
        d.last_pitch_index,
        d.loss_duration,
        d.plc_duration,
        d.last_frame_type,
        d.skip_plc,
        d.postfilter_period,
        d.postfilter_period_old,
        d.postfilter_tapset,
        d.postfilter_tapset_old,
        d.prefilter_and_fold,
    ];
    let mut vals: Vec<StateVal> = vec![
        StateVal::from(d.postfilter_gain),
        StateVal::from(d.postfilter_gain_old),
        StateVal::from(d.preemph_mem_d[0]),
        StateVal::from(d.preemph_mem_d[1]),
    ];
    #[cfg(feature = "qext")]
    vals.extend(d.qext_old_band_e.iter().map(|&v| StateVal::from(v)));
    for a in [
        &d.decode_mem,
        &d.old_ebands,
        &d.old_log_e,
        &d.old_log_e2,
        &d.background_log_e,
    ] {
        vals.extend(a.iter().map(|&v| StateVal::from(v)));
    }
    vals.extend(d.lpc.iter().map(|&v| StateVal::from(v)));
    CeltDecState { ints, vals }
}

#[track_caller]
fn assert_state_eq(ctx: &str, r: &CeltDecState, c: &CeltDecState) {
    assert_slice_eq(&format!("{ctx}: state ints"), &r.ints, &c.ints);
    assert_v(&format!("{ctx}: state values"), &r.vals, &c.vals);
}

// ---------------------------------------------------------------------------------------------
// Decoder pair
// ---------------------------------------------------------------------------------------------

/// A Rust and a C decoder driven in lockstep.
struct Pair<'m> {
    r: CeltDecoder<'m>,
    c: c::CeltDec,
    channels: usize,
    frames: usize,
    cov: Coverage,
}

/// Decoder paths seen by a [`Pair`] (sanity checks that the streams exercise what they claim).
#[derive(Debug, Default, Clone, Copy)]
struct Coverage {
    /// Frames decoded from a packet.
    normal: usize,
    /// Frames concealed with the noise PLC.
    plc_noise: usize,
    /// Frames concealed with the pitch PLC.
    plc_periodic: usize,
    /// Decoded frames with the post-filter on.
    postfilter: usize,
    /// Frames with non-zero output.
    nonzero: usize,
}

impl Pair<'static> {
    /// `celt_decoder_init(fs, channels)` on both sides, signalling off (as the Opus decoder).
    fn new(fs: i32, channels: i32) -> Self {
        let r = CeltDecoder::celt_decoder_init(fs, channels).unwrap();
        let c = c::CeltDec::new(fs, channels).unwrap();
        let mut p = Pair {
            r,
            c,
            channels: channels as usize,
            frames: 0,
            cov: Coverage::default(),
        };
        p.set(CELT_SET_SIGNALLING_REQUEST, 0);
        p.check_state("init");
        p
    }
}

impl Pair<'_> {
    /// Issues a SET ctl on both and compares the results.
    fn set(&mut self, request: i32, value: i32) {
        let rc = self.c.ctl_set(request, value);
        let rr = self.r.ctl_set(request, value);
        assert_eq!(code(rr.map(|()| 0)), rc, "ctl_set({request}, {value})");
    }

    fn check_state(&mut self, ctx: &str) {
        assert_state_eq(ctx, &rust_state(&self.r), &self.c.state());
    }

    /// Decodes one frame on both sides and compares everything.
    fn decode(
        &mut self,
        data: Option<&[u8]>,
        len: i32,
        frame_size: i32,
        accum: bool,
        qext: Option<&[u8]>,
        rng: &mut Rng,
        ctx: &str,
    ) -> i32 {
        let n_out = frame_size.max(0) as usize * self.channels;
        let mut pc = vec![Res::default(); n_out];
        if accum {
            for v in pc.iter_mut() {
                *v = res(0.5 * rng.f32_sym());
            }
        }
        let mut pr = pc.clone();
        let rc = self.c.decode(data, len, &mut pc, frame_size, accum, qext);
        let rr = rs_decode(&mut self.r, data, len, &mut pr, frame_size, accum, qext);
        let ctx = format!("{ctx} frame {}", self.frames);
        assert_eq!(code(rr), rc, "{ctx}: return value");
        assert_v(&format!("{ctx}: pcm"), &pr, &pc);
        assert_eq!(
            self.r.final_range(),
            self.c.ctl_get(sys::OPUS_GET_FINAL_RANGE_REQUEST).1 as u32,
            "{ctx}: final range"
        );
        self.check_state(&ctx);
        self.frames += 1;
        if rc > 0 {
            match self.r.last_frame_type {
                FRAME_NORMAL => self.cov.normal += 1,
                FRAME_PLC_NOISE => self.cov.plc_noise += 1,
                FRAME_PLC_PERIODIC => self.cov.plc_periodic += 1,
                _ => {}
            }
            if self.r.last_frame_type == FRAME_NORMAL
                && self.r.postfilter_gain != OpusVal16::default()
            {
                self.cov.postfilter += 1;
            }
            if pr.iter().any(|&v| v != Res::default()) {
                self.cov.nonzero += 1;
            }
        }
        rc
    }
}

const fn code(r: opusorus::Result<i32>) -> i32 {
    match r {
        Ok(v) => v,
        Err(e) => e.code(),
    }
}

#[allow(unused_variables, reason = "qext is only passed with the qext feature")]
fn rs_decode(
    d: &mut CeltDecoder<'_>,
    data: Option<&[u8]>,
    len: i32,
    pcm: &mut [Res],
    frame_size: i32,
    accum: bool,
    qext: Option<&[u8]>,
) -> opusorus::Result<i32> {
    #[cfg(feature = "qext")]
    {
        d.celt_decode_with_ec_dred(data, len, pcm, frame_size, None, accum, qext)
    }
    #[cfg(not(feature = "qext"))]
    {
        assert!(qext.is_none());
        d.celt_decode_with_ec(data, len, pcm, frame_size, None, accum)
    }
}

// ---------------------------------------------------------------------------------------------
// Signals and packet generation
// ---------------------------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Sig {
    Music,
    Speech,
    Noise,
    /// Tone plus periodic clicks (transients) and silent gaps.
    Clicks,
    /// Pure harmonic tone (pitch post-filter, periodic PLC).
    Tone,
    Silence,
}

fn gen_signal(sig: Sig, n: usize, ch: usize, fs: u32, seed: u64) -> Vec<f32> {
    match sig {
        Sig::Music => signals::music_like(n, ch, fs, seed),
        Sig::Speech => signals::speech_like(n, ch, fs, seed),
        Sig::Noise => signals::noise(n, ch, 0.3, seed),
        Sig::Silence => vec![0.0; n * ch],
        Sig::Tone | Sig::Clicks => {
            let mut rng = Rng::new(seed);
            let f0 = 90.0 + (seed % 200) as f64;
            let mut out = Vec::with_capacity(n * ch);
            for i in 0..n {
                let t = i as f64 / fs as f64;
                let mut v = 0.0f64;
                for k in 1..6 {
                    v += 0.12 / k as f64 * (2.0 * core::f64::consts::PI * f0 * k as f64 * t).sin();
                }
                if sig == Sig::Clicks {
                    let pos = i % (fs as usize / 7);
                    if pos < 40 {
                        v += 0.8 * rng.f32_sym() as f64;
                    }
                    if (i / (fs as usize / 3)) % 4 == 3 {
                        v *= 0.001;
                    }
                }
                for cch in 0..ch {
                    out.push((v * (1.0 - 0.2 * cch as f64)) as f32);
                }
            }
            out
        }
    }
}

/// Parses the output of the C encoder: `(main payload, QEXT payload)`.
fn split_packet(out: &[u8], ret: usize) -> (Vec<u8>, Option<Vec<u8>>) {
    let pkt = &out[1..1 + ret];
    if out[0] & 3 == 3 {
        assert_eq!(pkt[0], 0x41);
        let mut pos = 1;
        let mut padding = 0usize;
        loop {
            let p = pkt[pos] as usize;
            pos += 1;
            padding += if p == 255 { 254 } else { p };
            if p != 255 {
                break;
            }
        }
        let main_len = ret - pos - padding;
        let main = pkt[pos..pos + main_len].to_vec();
        let ext = &pkt[pos + main_len..];
        assert_eq!(ext[0], 124 << 1);
        (main, Some(ext[1..].to_vec()))
    } else {
        (pkt.to_vec(), None)
    }
}

/// Encoder configuration for a stream.
#[derive(Debug, Clone, Copy)]
struct EncCfg {
    fs: i32,
    channels: i32,
    frame_size: i32,
    /// Packet size in bytes (CBR) or the max size (VBR).
    nbytes: i32,
    /// VBR bitrate (0 = CBR).
    vbr_bitrate: i32,
    complexity: i32,
    start: i32,
    end: i32,
    sig: Sig,
    qext: bool,
    loss_perc: i32,
    prediction: i32,
}

impl EncCfg {
    const fn new(channels: i32, frame_size: i32, nbytes: i32, sig: Sig) -> Self {
        Self {
            fs: 48000,
            channels,
            frame_size,
            nbytes,
            vbr_bitrate: 0,
            complexity: 10,
            start: 0,
            end: 21,
            sig,
            qext: false,
            loss_perc: 0,
            prediction: 2,
        }
    }
}

fn make_encoder(cfg: &EncCfg) -> CeltEnc {
    let mut e = CeltEnc::new(cfg.fs, cfg.channels);
    assert_eq!(e.ctl(sys::OPUS_SET_COMPLEXITY_REQUEST, cfg.complexity), 0);
    if cfg.vbr_bitrate > 0 {
        assert_eq!(e.ctl(sys::OPUS_SET_VBR_REQUEST, 1), 0);
        assert_eq!(e.ctl(sys::OPUS_SET_BITRATE_REQUEST, cfg.vbr_bitrate), 0);
    }
    if cfg.start != 0 {
        assert_eq!(e.ctl(CELT_SET_START_BAND_REQUEST, cfg.start), 0);
    }
    if cfg.end != 21 {
        assert_eq!(e.ctl(CELT_SET_END_BAND_REQUEST, cfg.end), 0);
    }
    if cfg.qext {
        assert_eq!(e.ctl(sys::OPUS_SET_QEXT_REQUEST, 1), 0);
    }
    if cfg.loss_perc != 0 {
        assert_eq!(
            e.ctl(sys::OPUS_SET_PACKET_LOSS_PERC_REQUEST, cfg.loss_perc),
            0
        );
    }
    if cfg.prediction != 2 {
        assert_eq!(e.ctl(CELT_SET_PREDICTION_REQUEST, cfg.prediction), 0);
    }
    e
}

/// A generated packet: main payload plus optional QEXT payload.
type Packet = (Vec<u8>, Option<Vec<u8>>);

/// Encodes `nframes` frames of the configured signal with the C encoder.
fn gen_packets(cfg: &EncCfg, nframes: usize, seed: u64) -> Vec<Packet> {
    let mut e = make_encoder(cfg);
    let fsz = cfg.frame_size as usize;
    let ch = cfg.channels as usize;
    let pcm = gen_signal(cfg.sig, fsz * nframes, ch, cfg.fs as u32, seed);
    let mut rng = Rng::new(seed ^ 0x55);
    (0..nframes)
        .map(|i| {
            // Vary the CBR budget a little to exercise more allocations.
            let nbytes = if cfg.vbr_bitrate == 0 && cfg.nbytes > 8 {
                (cfg.nbytes + rng.range_i32(-3, 3)).clamp(2, if cfg.qext { 3825 } else { 1275 })
            } else {
                cfg.nbytes
            };
            let (ret, out) = e.encode(
                &pcm[i * fsz * ch..(i + 1) * fsz * ch],
                cfg.frame_size,
                nbytes,
            );
            assert!(ret > 0, "encode failed: {ret} ({cfg:?})");
            split_packet(&out, ret as usize)
        })
        .collect()
}

/// Loss patterns.
#[derive(Debug, Clone, Copy)]
enum Loss {
    None,
    /// Independent random losses with the given percentage.
    Random(i32),
    /// Bursts of up to the given length.
    Bursts(usize),
    /// Every other packet lost (skip_plc stays set).
    Alternate,
}

fn loss_mask(loss: Loss, n: usize, rng: &mut Rng) -> Vec<bool> {
    let mut m = vec![false; n];
    match loss {
        Loss::None => {}
        Loss::Random(p) => {
            for v in m.iter_mut() {
                *v = rng.range_i32(0, 99) < p;
            }
        }
        Loss::Bursts(max) => {
            let mut i = 3;
            while i < n {
                let len = rng.range_i32(1, max as i32) as usize;
                for v in m.iter_mut().skip(i).take(len) {
                    *v = true;
                }
                i += len + rng.range_i32(1, 12) as usize;
            }
        }
        Loss::Alternate => {
            for (i, v) in m.iter_mut().enumerate() {
                *v = i % 2 == 1;
            }
        }
    }
    m
}

/// Decodes a packet stream on a pair with the given loss pattern.
fn run_stream(
    pair: &mut Pair<'_>,
    pkts: &[Packet],
    out_frame: i32,
    loss: Loss,
    seed: u64,
    ctx: &str,
) {
    let mut rng = Rng::new(seed);
    let mask = loss_mask(loss, pkts.len(), &mut rng);
    for (i, (main, ext)) in pkts.iter().enumerate() {
        if mask[i] {
            pair.decode(None, 0, out_frame, false, None, &mut rng, ctx);
        } else {
            let ret = pair.decode(
                Some(main),
                main.len() as i32,
                out_frame,
                false,
                ext.as_deref(),
                &mut rng,
                ctx,
            );
            assert_eq!(ret, out_frame, "{ctx}: frame {i} decoded size");
        }
    }
}

// ---------------------------------------------------------------------------------------------
// CTLs, init, errors
// ---------------------------------------------------------------------------------------------

#[test]
fn init_and_ctls() {
    for &fs in &[48000, 24000, 16000, 12000, 8000] {
        for ch in 1..=2 {
            let mut p = Pair::new(fs, ch);
            let ctx = format!("fs={fs} ch={ch}");
            // GET requests.
            for req in [
                OPUS_GET_COMPLEXITY_REQUEST,
                CELT_GET_AND_CLEAR_ERROR_REQUEST,
                OPUS_GET_LOOKAHEAD_REQUEST,
                OPUS_GET_PITCH_REQUEST,
                OPUS_GET_FINAL_RANGE_REQUEST,
                OPUS_GET_PHASE_INVERSION_DISABLED_REQUEST,
            ] {
                let (rc, vc) = p.c.ctl_get(req);
                let rr = p.r.ctl_get(req);
                assert_eq!(code(rr), if rc == 0 { vc } else { rc }, "{ctx}: get {req}");
            }
            assert!(p.c.get_mode_ok());
            assert!(core::ptr::eq(
                p.r.mode(),
                opus_custom_mode_create(48000, 960).unwrap()
            ));
            // SET requests, valid and invalid values.
            for (req, vals) in [
                (OPUS_SET_COMPLEXITY_REQUEST, &[-1, 0, 5, 10, 11][..]),
                (CELT_SET_START_BAND_REQUEST, &[-1, 0, 17, 20, 21, 0][..]),
                (CELT_SET_END_BAND_REQUEST, &[0, 1, 13, 21, 22, 21][..]),
                (CELT_SET_CHANNELS_REQUEST, &[0, 1, 2, 3, ch][..]),
                (CELT_SET_SIGNALLING_REQUEST, &[0, 1, 0][..]),
                (
                    OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST,
                    &[-1, 0, 1, 2][..],
                ),
            ] {
                for &v in vals {
                    p.set(req, v);
                    p.check_state(&format!("{ctx}: set {req}={v}"));
                }
            }
            for req in [
                OPUS_GET_COMPLEXITY_REQUEST,
                OPUS_GET_PHASE_INVERSION_DISABLED_REQUEST,
            ] {
                let (rc, vc) = p.c.ctl_get(req);
                assert_eq!(rc, 0);
                assert_eq!(p.r.ctl_get(req).unwrap(), vc);
            }
            assert_eq!(p.r.lookahead(), p.c.ctl_get(OPUS_GET_LOOKAHEAD_REQUEST).1);
            // Unknown requests.
            for req in [4000, 4002, 10002, 12345] {
                assert_eq!(p.c.ctl_set(req, 0), sys::OPUS_UNIMPLEMENTED);
                assert_eq!(p.r.ctl_set(req, 0), Err(opusorus::Error::Unimplemented));
                assert_eq!(p.r.ctl_get(req), Err(opusorus::Error::Unimplemented));
            }
            p.set(OPUS_RESET_STATE, 0);
            p.check_state(&format!("{ctx}: reset"));
        }
    }
    // Invalid init.
    assert_eq!(
        CeltDecoder::celt_decoder_init(48000, 3).err(),
        Some(opusorus::Error::BadArg)
    );
    assert_eq!(c::CeltDec::new(48000, 3).err(), Some(sys::OPUS_BAD_ARG));
    assert!(CeltDecoder::celt_decoder_init(48000, 0).is_err());
    assert!(celt_decoder_get_size(2) > celt_decoder_get_size(1));
}

#[test]
fn error_returns() {
    let mut rng = Rng::new(7);
    let pkts = gen_packets(&EncCfg::new(2, 960, 160, Sig::Music), 4, 1);
    let mut p = Pair::new(48000, 2);
    let data = &pkts[0].0;
    // Frame sizes that are not a CELT frame size.
    for fsz in [0, 100, 121, 1920, -960] {
        p.decode(
            Some(data),
            data.len() as i32,
            fsz,
            false,
            None,
            &mut rng,
            "bad frame size",
        );
    }
    // Lengths out of range.
    let big = vec![0u8; 1300];
    p.decode(Some(&big), 1276, 960, false, None, &mut rng, "len 1276");
    p.decode(Some(&big), -1, 960, false, None, &mut rng, "len -1");
    p.decode(None, -1, 960, false, None, &mut rng, "NULL len -1");
    p.decode(None, 1276, 960, false, None, &mut rng, "NULL len 1276");
    // Rust-only guards.
    let mut small = vec![Res::default(); 100];
    assert_eq!(
        p.r.celt_decode_with_ec(Some(data), data.len() as i32, &mut small, 960, None, false),
        Err(opusorus::Error::BadArg)
    );
    assert_eq!(
        p.r.celt_decode_with_ec(
            Some(&data[..3]),
            10,
            &mut vec![Res::default(); 1920],
            960,
            None,
            false
        ),
        Err(opusorus::Error::BadArg)
    );
    // The decoder still works after errors.
    for (m, _) in &pkts {
        p.decode(
            Some(m),
            m.len() as i32,
            960,
            false,
            None,
            &mut rng,
            "after errors",
        );
    }
}

// ---------------------------------------------------------------------------------------------
// Static helpers
// ---------------------------------------------------------------------------------------------

#[test]
fn tf_decode_random() {
    let mut rng = Rng::new(0x7F);
    for iter in 0..6000 {
        let len = rng.range_i32(0, 40) as usize;
        let mut buf = vec![0u8; len];
        rng.fill_bytes(&mut buf);
        let lm = rng.range_i32(0, 3);
        let tr = rng.range_i32(0, 1) == 1;
        let start = if rng.range_i32(0, 3) == 0 { 17 } else { 0 };
        let end = rng.range_i32(start + 1, 21);
        let pre = rng.range_i32(0, (len as i32 * 8).min(300));
        let mut tc = vec![-99; 21];
        let ec = c::tf_decode(start, end, tr, &mut tc, lm, &buf, pre);
        let mut tr_ = vec![-99; 21];
        let mut d = EcDec::new(&buf);
        for _ in 0..pre {
            d.dec_bit_logp(1);
        }
        tf_decode(start, end, tr, &mut tr_, lm, &mut d);
        assert_slice_eq(&format!("tf_decode iter {iter}"), &tr_, &tc);
        assert_eq!([d.rng, d.tell() as u32], ec, "tf_decode iter {iter}: ec");
    }
}

fn preemph_coefs() -> Vec<[OpusVal16; 4]> {
    #[cfg_attr(
        not(any(feature = "qext", feature = "custom-modes")),
        expect(unused_mut, reason = "only extended with features")
    )]
    let mut v = vec![opus_custom_mode_create(48000, 960).unwrap().preemph];
    #[cfg(feature = "qext")]
    v.push(opus_custom_mode_create(96000, 1920).unwrap().preemph);
    #[cfg(feature = "custom-modes")]
    {
        // Custom-mode pre-emphasis filters (coef[1] != 0 path): 8, 16 and 32 kHz modes.
        use opusorus::celt::modes::opus_custom_mode_create_custom;
        for (fs, frame) in [(8000, 160), (16000, 320), (32000, 640)] {
            v.push(opus_custom_mode_create_custom(fs, frame).unwrap().preemph);
        }
    }
    v
}

#[test]
fn deemphasis_random() {
    let mut rng = Rng::new(0xDE);
    let coefs = preemph_coefs();
    for iter in 0..3000 {
        let lm = rng.range_i32(0, 3);
        let n = 120usize << lm;
        let c = rng.range_i32(1, 2) as usize;
        let ds = [1, 1, 2, 3, 4, 6][rng.range_i32(0, 5) as usize];
        let accum = rng.range_i32(0, 2) == 0;
        let coef = coefs[rng.range_i32(0, coefs.len() as i32 - 1) as usize];
        let amp = [1.0f32, 3000.0, 32768.0, 1e6, 1e-30, 4e-29][rng.range_i32(0, 5) as usize];
        // The decoder's signals are saturated to SIG_SAT (`sig`), its memories smaller.
        let in0: Vec<CeltSig> = gen_vals(n, &mut rng, |r| sig(amp * r.f32_sym()));
        let in1: Vec<CeltSig> = gen_vals(n, &mut rng, |r| sig(amp * r.f32_sym()));
        let mut mem = [
            sig(mem_amp(amp) * rng.f32_sym()),
            sig(mem_amp(amp) * rng.f32_sym()),
        ];
        let mut pcm: Vec<Res> = gen_vals(n * c, &mut rng, |r| res(r.f32_sym()));
        let mut mem_r = mem;
        let mut pcm_r = pcm.clone();
        c::deemphasis(&in0, &in1, &mut pcm, n, c, ds, &coef, &mut mem, accum);
        let mut scratch = vec![CeltSig::default(); n];
        let ins: [&[CeltSig]; 2] = [&in0, &in1];
        deemphasis(
            &ins[..c],
            &mut pcm_r,
            n,
            c,
            ds,
            &coef,
            &mut mem_r,
            accum,
            &mut scratch,
        );
        let ctx = format!("deemphasis iter {iter} n={n} c={c} ds={ds} accum={accum}");
        assert_v(&ctx, &pcm_r, &pcm);
        assert_v(&ctx, &mem_r, &mem);
    }
}

#[test]
fn celt_synthesis_random() {
    let mut rng = Rng::new(0x5EED);
    let mut fss = vec![48000];
    if cfg!(feature = "qext") {
        fss.push(96000);
    }
    for iter in 0..1500 {
        let fs = fss[rng.range_i32(0, fss.len() as i32 - 1) as usize];
        let mode: &CeltMode = opus_custom_mode_create(fs, fs / 50).unwrap();
        let lm = rng.range_i32(0, 3);
        let n = (mode.short_mdct_size << lm) as usize;
        let overlap = mode.overlap as usize;
        let nb = mode.nb_ebands as usize;
        let (c_, cc) = [(1, 1), (2, 2), (1, 2), (2, 1)][rng.range_i32(0, 3) as usize];
        let tr = lm > 0 && rng.range_i32(0, 1) == 1;
        let ds = if fs == 48000 {
            [1, 1, 2, 3, 4, 6][rng.range_i32(0, 5) as usize]
        } else {
            1
        };
        let silence = rng.range_i32(0, 9) == 0;
        let start = if rng.range_i32(0, 3) == 0 { 17 } else { 0 };
        let eff_end = rng.range_i32(start + 1, mode.eff_ebands);
        let use_qext = cfg!(feature = "qext") && rng.range_i32(0, 1) == 1;
        let qext_end = if rng.range_i32(0, 1) == 1 { 14 } else { 2 };
        let mut x: Vec<CeltNorm> = gen_vals(2 * n, &mut rng, |r| nrm(XAMP * r.f32_sym()));
        let mut obe: Vec<CeltGlog> = gen_vals(2 * nb, &mut rng, |r| glog(EAMP * r.f32_sym()));
        let mut qble: Vec<CeltGlog> = gen_vals(28, &mut rng, |r| glog(8.0 * r.f32_sym()));
        let off = 37;
        let blen = off + n + overlap;
        let mut o0: Vec<CeltSig> = gen_vals(blen, &mut rng, |r| sig(1000.0 * r.f32_sym()));
        let mut o1: Vec<CeltSig> = gen_vals(blen, &mut rng, |r| sig(1000.0 * r.f32_sym()));
        let (mut r0, mut r1) = (o0.clone(), o1.clone());
        let (xr, obr, qbr) = (x.clone(), obe.clone(), qble.clone());
        c::celt_synthesis(
            fs,
            &mut x,
            &mut o0,
            if cc == 2 { Some(&mut o1) } else { None },
            off,
            &mut obe,
            start,
            eff_end,
            c_,
            cc,
            tr,
            lm,
            ds,
            silence,
            use_qext,
            &mut qble,
            qext_end,
        );
        #[cfg(feature = "qext")]
        let qm = opusorus::celt::modes::compute_qext_mode(mode);
        let mut freq = vec![CeltSig::default(); n];
        {
            let mut outs: [&mut [CeltSig]; 2] = [&mut r0[off..], &mut r1[off..]];
            celt_synthesis(
                mode,
                &xr,
                &mut outs[..cc as usize],
                &obr,
                start,
                eff_end,
                c_,
                cc,
                tr,
                lm,
                ds,
                silence,
                #[cfg(feature = "qext")]
                if use_qext { Some(&qm) } else { None },
                #[cfg(feature = "qext")]
                &qbr,
                #[cfg(feature = "qext")]
                qext_end,
                &mut freq,
            );
        }
        #[cfg(not(feature = "qext"))]
        let _ = (&qbr, qext_end);
        let ctx = format!(
            "synthesis iter {iter} fs={fs} lm={lm} C={c_} CC={cc} tr={tr} ds={ds} sil={silence} \
             start={start} end={eff_end} qext={use_qext}"
        );
        assert_v(&format!("{ctx}: out0"), &r0, &o0);
        if cc == 2 {
            assert_v(&format!("{ctx}: out1"), &r1, &o1);
        }
    }
}

#[test]
fn plc_pitch_search_random() {
    let mut rng = Rng::new(0x9177);
    let mut fss = vec![48000];
    if cfg!(feature = "qext") {
        fss.push(96000);
    }
    for iter in 0..150 {
        let fs = fss[iter % fss.len()];
        let dbs = if fs == 96000 { 4096 } else { 2048 };
        let c_ = rng.range_i32(1, 2);
        let kind = [Sig::Speech, Sig::Tone, Sig::Music, Sig::Noise][iter % 4];
        let s = gen_signal(kind, dbs, 2, fs as u32, iter as u64);
        let mut m0: Vec<CeltSig> = s.iter().step_by(2).map(|v| sig(v * 32768.0)).collect();
        let mut m1: Vec<CeltSig> = s
            .iter()
            .skip(1)
            .step_by(2)
            .map(|v| sig(v * 32768.0))
            .collect();
        let rc = c::plc_pitch_search(fs, &mut m0, &mut m1, c_);
        let mut lp = vec![OpusVal16::default(); 1024];
        let chans: [&[CeltSig]; 2] = [&m0, &m1];
        let qext_scale = if fs == 96000 { 2 } else { 1 };
        let rr = celt_plc_pitch_search(&chans[..c_ as usize], c_ as usize, qext_scale, &mut lp);
        assert_eq!(rr, rc, "pitch search iter {iter} fs={fs} C={c_}");
    }
}

// ---------------------------------------------------------------------------------------------
// Streams
// ---------------------------------------------------------------------------------------------

#[test]
fn streams_frame_sizes_and_budgets() {
    let mut seed = 1u64;
    for &ch in &[1, 2] {
        for &fsz in &[120, 240, 480, 960] {
            for &(nbytes, vbr) in &[
                (2, 0),
                (5, 0),
                (12, 0),
                (40, 0),
                (0, 24000),
                (160, 0),
                (0, 96000),
                (400, 0),
                (1275, 0),
            ] {
                let sig = [
                    Sig::Music,
                    Sig::Speech,
                    Sig::Clicks,
                    Sig::Noise,
                    Sig::Tone,
                    Sig::Silence,
                ][seed as usize % 6];
                let mut cfg = EncCfg::new(ch, fsz, if vbr > 0 { 1275 } else { nbytes }, sig);
                cfg.vbr_bitrate = vbr;
                cfg.complexity = [10, 5, 0, 8][seed as usize % 4];
                let nframes = (19200 / fsz as usize).clamp(20, 80);
                let pkts = gen_packets(&cfg, nframes, seed);
                let mut p = Pair::new(48000, ch);
                run_stream(&mut p, &pkts, fsz, Loss::None, seed, &format!("{cfg:?}"));
                seed += 1;
            }
        }
    }
}

#[test]
fn streams_long_with_state_evolution() {
    // Long streams: post-filter (voiced/tonal), transients, energy prediction.
    for (i, &(ch, fsz, sig, nbytes, vbr)) in [
        (1, 960, Sig::Speech, 0, 32000),
        (2, 960, Sig::Music, 0, 128000),
        (2, 480, Sig::Clicks, 120, 0),
        (1, 240, Sig::Tone, 60, 0),
        (2, 120, Sig::Speech, 0, 64000),
    ]
    .iter()
    .enumerate()
    {
        let mut cfg = EncCfg::new(ch, fsz, if vbr > 0 { 1275 } else { nbytes }, sig);
        cfg.vbr_bitrate = vbr;
        let nframes = 48000 * 3 / fsz as usize;
        let pkts = gen_packets(&cfg, nframes, 100 + i as u64);
        let mut p = Pair::new(48000, ch);
        run_stream(&mut p, &pkts, fsz, Loss::None, 7, &format!("long {cfg:?}"));
        let cov = p.cov;
        assert_eq!(cov.normal, nframes, "{cov:?}");
        assert!(cov.nonzero > nframes * 9 / 10, "{cov:?}");
        if matches!(sig, Sig::Speech | Sig::Tone) {
            assert!(
                cov.postfilter > nframes / 20,
                "post-filter rarely on: {cov:?}"
            );
        }
    }
}

#[test]
fn streams_postfilter_prediction_and_stereo_modes() {
    let mut seed = 300u64;
    // Low-rate stereo (intensity), mid-rate (dual stereo), prediction off/intra-only, packet
    // loss adaptation in the encoder.
    for &(nbytes, pred, loss_perc, sig) in &[
        (20, 2, 0, Sig::Music),
        (35, 2, 0, Sig::Speech),
        (70, 1, 0, Sig::Music),
        (110, 0, 0, Sig::Speech),
        (90, 2, 20, Sig::Tone),
        (250, 2, 0, Sig::Noise),
    ] {
        for &fsz in &[240, 960] {
            let mut cfg = EncCfg::new(2, fsz, nbytes, sig);
            cfg.prediction = pred;
            cfg.loss_perc = loss_perc;
            let pkts = gen_packets(&cfg, 60, seed);
            let mut p = Pair::new(48000, 2);
            run_stream(&mut p, &pkts, fsz, Loss::None, seed, &format!("{cfg:?}"));
            // Phase inversion disabled.
            let mut p = Pair::new(48000, 2);
            p.set(OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST, 1);
            run_stream(
                &mut p,
                &pkts,
                fsz,
                Loss::None,
                seed,
                &format!("noinv {cfg:?}"),
            );
            seed += 1;
        }
    }
}

#[test]
fn streams_channel_conversion() {
    let mut seed = 500u64;
    for &(enc_ch, dec_ch) in &[(1, 2), (2, 1)] {
        for &fsz in &[120, 480, 960] {
            for &nbytes in &[16, 80, 300] {
                let cfg = EncCfg::new(enc_ch, fsz, nbytes, Sig::Music);
                let pkts = gen_packets(&cfg, 30, seed);
                let mut p = Pair::new(48000, dec_ch);
                p.set(CELT_SET_CHANNELS_REQUEST, enc_ch);
                run_stream(
                    &mut p,
                    &pkts,
                    fsz,
                    Loss::Random(15),
                    seed,
                    &format!("conv {enc_ch}->{dec_ch} {cfg:?}"),
                );
                seed += 1;
            }
        }
    }
}

#[test]
fn streams_downsampled_outputs() {
    let mut seed = 700u64;
    for &fs in &[24000, 16000, 12000, 8000] {
        let ds = 48000 / fs;
        for &ch in &[1, 2] {
            for &fsz in &[120, 240, 960] {
                let cfg = EncCfg::new(ch, fsz, 60 * ch, Sig::Speech);
                let pkts = gen_packets(&cfg, 25, seed);
                let mut p = Pair::new(fs, ch);
                run_stream(
                    &mut p,
                    &pkts,
                    fsz / ds,
                    Loss::Bursts(3),
                    seed,
                    &format!("fs={fs} {cfg:?}"),
                );
                // accum
                let mut rng = Rng::new(seed);
                for (m, _) in pkts.iter().take(6) {
                    p.decode(
                        Some(m),
                        m.len() as i32,
                        fsz / ds,
                        true,
                        None,
                        &mut rng,
                        "accum ds",
                    );
                }
                p.decode(None, 0, fsz / ds, true, None, &mut rng, "accum ds lost");
                seed += 1;
            }
        }
    }
}

#[test]
fn streams_end_band_limits() {
    let mut seed = 900u64;
    for &end in &[13, 17, 19, 20] {
        for &ch in &[1, 2] {
            for &fsz in &[240, 960] {
                let mut cfg = EncCfg::new(ch, fsz, 70, Sig::Music);
                cfg.end = end;
                let pkts = gen_packets(&cfg, 25, seed);
                let mut p = Pair::new(48000, ch);
                p.set(CELT_SET_END_BAND_REQUEST, end);
                run_stream(
                    &mut p,
                    &pkts,
                    fsz,
                    Loss::Random(10),
                    seed,
                    &format!("end={end} {cfg:?}"),
                );
                seed += 1;
            }
        }
    }
}

#[test]
fn streams_hybrid_shared_range_decoder() {
    let mut seed = 1100u64;
    for &ch in &[1, 2] {
        for &fsz in &[480, 960] {
            for &(end, nbytes) in &[(19, 60), (21, 90), (21, 30), (20, 40)] {
                let mut cfg = EncCfg::new(ch, fsz, nbytes, Sig::Speech);
                cfg.start = 17;
                cfg.end = end;
                let mut e = make_encoder(&cfg);
                let mut p = Pair::new(48000, ch);
                p.set(CELT_SET_START_BAND_REQUEST, 17);
                p.set(CELT_SET_END_BAND_REQUEST, end);
                let pcm = gen_signal(Sig::Speech, fsz as usize * 30, ch as usize, 48000, seed);
                let mut rng = Rng::new(seed);
                let fsu = fsz as usize * ch as usize;
                for f in 0..30 {
                    // "SILK" symbols first.
                    let nsym = rng.range_i32(0, nbytes / 4) as usize;
                    let fts: Vec<u32> = (0..nsym).map(|_| rng.range_i32(2, 5000) as u32).collect();
                    let vals: Vec<u32> = fts.iter().map(|&ft| rng.next_u32() % ft).collect();
                    let (ret, out) =
                        e.encode_shared(&pcm[f * fsu..(f + 1) * fsu], fsz, nbytes, &fts, &vals);
                    assert!(ret > 0, "hybrid encode {ret}");
                    let data = &out[..ret as usize];
                    let ctx = format!("hybrid ch={ch} fsz={fsz} end={end} frame {f}");
                    if rng.range_i32(0, 9) == 0 {
                        p.decode(None, 0, fsz, false, None, &mut rng, &ctx);
                        continue;
                    }
                    let accum = rng.range_i32(0, 3) == 0;
                    let mut pc: Vec<Res> = gen_vals(fsu, &mut rng, |r| res(r.f32_sym()));
                    let mut pr = pc.clone();
                    let (rc, vc, ecc) = p.c.decode_shared(data, &mut pc, fsz, accum, &fts);
                    assert_eq!(vc, vals, "{ctx}: SILK symbols");
                    let mut d = EcDec::new(data);
                    let vr: Vec<u32> = fts.iter().map(|&ft| d.dec_uint(ft)).collect();
                    assert_eq!(vr, vals);
                    let rr = p.r.celt_decode_with_ec(
                        Some(data),
                        data.len() as i32,
                        &mut pr,
                        fsz,
                        Some(&mut d),
                        accum,
                    );
                    assert_eq!(code(rr), rc, "{ctx}: ret");
                    assert_v(&ctx, &pr, &pc);
                    assert_eq!(
                        [d.rng, d.tell() as u32, d.tell_frac(), d.error as u32],
                        ecc,
                        "{ctx}: shared ec"
                    );
                    p.check_state(&ctx);
                }
            }
            seed += 1;
        }
    }
}

#[test]
fn streams_packet_loss() {
    let mut seed = 1300u64;
    let mut total = Coverage::default();
    for &ch in &[1, 2] {
        for &fsz in &[120, 240, 480, 960] {
            for (li, &loss) in [
                Loss::Random(20),
                Loss::Bursts(2),
                Loss::Bursts(12),
                Loss::Alternate,
            ]
            .iter()
            .enumerate()
            {
                let sig = [Sig::Tone, Sig::Speech, Sig::Music, Sig::Clicks][li];
                let cfg = EncCfg::new(ch, fsz, 50 * ch, sig);
                let nframes = (48000 / fsz as usize).max(60);
                let pkts = gen_packets(&cfg, nframes, seed);
                let mut p = Pair::new(48000, ch);
                run_stream(
                    &mut p,
                    &pkts,
                    fsz,
                    loss,
                    seed,
                    &format!("loss {loss:?} {cfg:?}"),
                );
                total.plc_noise += p.cov.plc_noise;
                total.plc_periodic += p.cov.plc_periodic;
                seed += 1;
            }
        }
    }
    assert!(total.plc_noise > 5 && total.plc_periodic > 100, "{total:?}");
    // Loss straight after init (skip_plc = 1) and a very long loss (noise PLC saturation).
    let cfg = EncCfg::new(2, 960, 100, Sig::Tone);
    let pkts = gen_packets(&cfg, 12, 77);
    let mut p = Pair::new(48000, 2);
    let mut rng = Rng::new(1);
    for _ in 0..3 {
        p.decode(None, 0, 960, false, None, &mut rng, "initial loss");
    }
    for (m, _) in &pkts[..4] {
        p.decode(Some(m), m.len() as i32, 960, false, None, &mut rng, "good");
    }
    for _ in 0..40 {
        p.decode(None, 0, 960, false, None, &mut rng, "long loss");
    }
    for (m, _) in &pkts[4..] {
        p.decode(
            Some(m),
            m.len() as i32,
            960,
            false,
            None,
            &mut rng,
            "recovery",
        );
    }
    // Lost frames with a different frame size than the stream, and len <= 1 packets.
    for (i, (m, _)) in pkts.iter().enumerate() {
        p.decode(Some(m), m.len() as i32, 960, false, None, &mut rng, "good2");
        let fsz = [120, 240, 480, 960][i % 4];
        p.decode(Some(&m[..1]), 1, fsz, false, None, &mut rng, "len 1");
        p.decode(Some(m), 0, fsz, false, None, &mut rng, "len 0");
    }
}

/// Many random configurations: channels and channel conversion, frame size, CBR/VBR budget,
/// complexity, end band, output rate, loss pattern, accumulation and resets.
#[test]
fn streams_random_configs() {
    let mut rng = Rng::new(0xC0FFEE);
    let sigs = [
        Sig::Music,
        Sig::Speech,
        Sig::Noise,
        Sig::Clicks,
        Sig::Tone,
        Sig::Silence,
    ];
    let mut total = Coverage::default();
    for iter in 0..800u64 {
        let ch = rng.range_i32(1, 2);
        let dec_ch = if rng.range_i32(0, 4) == 0 { 3 - ch } else { ch };
        let fsz = 120 << rng.range_i32(0, 3);
        let sig = sigs[rng.range_i32(0, sigs.len() as i32 - 1) as usize];
        let mut cfg = EncCfg::new(ch, fsz, 0, sig);
        if rng.range_i32(0, 2) == 0 {
            cfg.vbr_bitrate = rng.range_i32(6000, 256000);
            cfg.nbytes = 1275;
        } else {
            cfg.nbytes = [
                rng.range_i32(2, 30),
                rng.range_i32(20, 200),
                rng.range_i32(100, 1275),
            ][rng.range_i32(0, 2) as usize];
        }
        cfg.complexity = rng.range_i32(0, 10);
        if rng.range_i32(0, 3) == 0 {
            cfg.end = [13, 17, 19, 20][rng.range_i32(0, 3) as usize];
        }
        cfg.prediction = [2, 2, 2, 1, 0][rng.range_i32(0, 4) as usize];
        cfg.loss_perc = [0, 0, 5, 25][rng.range_i32(0, 3) as usize];
        let fs = [48000, 48000, 24000, 16000, 12000, 8000][rng.range_i32(0, 5) as usize];
        let ds = 48000 / fs;
        let loss = [
            Loss::None,
            Loss::Random(10),
            Loss::Random(40),
            Loss::Bursts(3),
            Loss::Bursts(20),
            Loss::Alternate,
        ][rng.range_i32(0, 5) as usize];
        let nframes = rng.range_i32(10, 60) as usize;
        let pkts = gen_packets(&cfg, nframes, iter);
        let mut p = Pair::new(fs, dec_ch);
        if dec_ch != ch {
            p.set(CELT_SET_CHANNELS_REQUEST, ch);
        }
        if cfg.end != 21 {
            p.set(CELT_SET_END_BAND_REQUEST, cfg.end);
        }
        if rng.range_i32(0, 3) == 0 {
            p.set(
                OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST,
                1 - p.r.disable_inv,
            );
        }
        let ctx = format!("random {iter}: dec fs={fs} ch={dec_ch} {loss:?} {cfg:?}");
        let mask = loss_mask(loss, nframes, &mut rng);
        for (i, (m, _)) in pkts.iter().enumerate() {
            let accum = rng.range_i32(0, 5) == 0;
            if mask[i] {
                p.decode(None, 0, fsz / ds, accum, None, &mut rng, &ctx);
            } else {
                p.decode(
                    Some(m),
                    m.len() as i32,
                    fsz / ds,
                    accum,
                    None,
                    &mut rng,
                    &ctx,
                );
            }
            if rng.range_i32(0, 60) == 0 {
                p.set(OPUS_RESET_STATE, 0);
            }
        }
        total.normal += p.cov.normal;
        total.plc_noise += p.cov.plc_noise;
        total.plc_periodic += p.cov.plc_periodic;
        total.postfilter += p.cov.postfilter;
    }
    assert!(
        total.plc_noise > 50 && total.plc_periodic > 100 && total.postfilter > 100,
        "{total:?}"
    );
}

#[test]
fn streams_hybrid_loss_noise_plc() {
    // start != 0 forces the noise PLC.
    let mut cfg = EncCfg::new(2, 960, 80, Sig::Speech);
    cfg.start = 17;
    let pkts = gen_packets(&cfg, 40, 99);
    let mut p = Pair::new(48000, 2);
    p.set(CELT_SET_START_BAND_REQUEST, 17);
    run_stream(&mut p, &pkts, 960, Loss::Bursts(4), 99, "hybrid noise plc");
}

#[test]
fn streams_corrupted_packets() {
    let mut rng = Rng::new(0xC0);
    for &ch in &[1, 2] {
        for &fsz in &[120, 240, 480, 960] {
            let cfg = EncCfg::new(ch, fsz, 80, Sig::Music);
            let pkts = gen_packets(&cfg, 150, fsz as u64 + ch as u64);
            let mut p = Pair::new(48000, ch);
            for (i, (m, _)) in pkts.iter().enumerate() {
                let mut m = m.clone();
                match i % 5 {
                    0 => {}
                    1 => {
                        // bit flips
                        for _ in 0..rng.range_i32(1, 6) {
                            let b = rng.range_i32(0, m.len() as i32 * 8 - 1) as usize;
                            m[b / 8] ^= 1 << (b % 8);
                        }
                    }
                    2 => {
                        // truncation
                        let l = rng.range_i32(2, m.len() as i32) as usize;
                        m.truncate(l);
                    }
                    3 => rng.fill_bytes(&mut m),
                    _ => {
                        // random length garbage
                        let mut g = vec![0u8; rng.range_i32(2, 1275) as usize];
                        rng.fill_bytes(&mut g);
                        m = g;
                    }
                }
                p.decode(
                    Some(&m),
                    m.len() as i32,
                    fsz,
                    false,
                    None,
                    &mut rng,
                    "corrupt",
                );
                // CELT_GET_AND_CLEAR_ERROR sometimes.
                if i % 7 == 0 {
                    let (rc, vc) = p.c.ctl_get(CELT_GET_AND_CLEAR_ERROR_REQUEST);
                    assert_eq!(rc, 0);
                    assert_eq!(p.r.get_and_clear_error(), vc);
                }
            }
        }
    }
    // Silence flag packets and all-zero / all-ones payloads.
    let mut p = Pair::new(48000, 2);
    for (i, pkt) in [
        vec![0x80u8, 0, 0, 0],
        vec![0xFF; 8],
        vec![0; 8],
        vec![0x7F, 0xFF, 0x00, 0x12],
        vec![0; 1275],
        vec![0xFF; 1275],
    ]
    .iter()
    .enumerate()
    {
        for &fsz in &[120, 960] {
            p.decode(
                Some(pkt),
                pkt.len() as i32,
                fsz,
                false,
                None,
                &mut rng,
                &format!("special {i}"),
            );
        }
    }
}

#[test]
fn streams_accum_and_reset() {
    let mut seed = 1500u64;
    for &ch in &[1, 2] {
        for &fsz in &[240, 960] {
            let cfg = EncCfg::new(ch, fsz, 90, Sig::Speech);
            let pkts = gen_packets(&cfg, 40, seed);
            let mut p = Pair::new(48000, ch);
            let mut rng = Rng::new(seed);
            for (i, (m, _)) in pkts.iter().enumerate() {
                let accum = i % 3 != 0;
                if i % 9 == 4 {
                    p.decode(None, 0, fsz, accum, None, &mut rng, "accum lost");
                } else {
                    p.decode(Some(m), m.len() as i32, fsz, accum, None, &mut rng, "accum");
                }
                if i % 13 == 12 {
                    p.set(OPUS_RESET_STATE, 0);
                    p.check_state("reset");
                }
                if i % 11 == 5 {
                    // Complexity has no effect on the decoder without deep PLC.
                    p.set(OPUS_SET_COMPLEXITY_REQUEST, (i % 11) as i32);
                }
            }
            seed += 1;
        }
    }
}

// ---------------------------------------------------------------------------------------------
// QEXT
// ---------------------------------------------------------------------------------------------

#[cfg(feature = "qext")]
#[test]
fn qext_streams() {
    assert!(c::has_qext());
    let mut seed = 2000u64;
    let mut total_ext = 0;
    // 96 kHz mode (with and without extension payload) and 48 kHz with extension payloads.
    for &fs in &[96000, 48000] {
        for &ch in &[1, 2] {
            let base = fs / 400;
            for &lm in &[0, 1, 2, 3] {
                let fsz = base << lm;
                for &(qext, nbytes) in &[(true, 900), (true, 300), (false, 200), (true, 2500)] {
                    let mut cfg = EncCfg::new(ch, fsz, nbytes * (1 << lm) / 8 + 40, Sig::Music);
                    cfg.fs = fs;
                    cfg.qext = qext;
                    cfg.nbytes = cfg.nbytes.min(3825);
                    let pkts = gen_packets(&cfg, 16, seed);
                    let n_ext = pkts.iter().filter(|p| p.1.is_some()).count();
                    if !qext {
                        assert_eq!(n_ext, 0, "qext payloads: {cfg:?}");
                    }
                    total_ext += n_ext;
                    let mut p = Pair::new(fs, ch);
                    run_stream(
                        &mut p,
                        &pkts,
                        fsz,
                        Loss::Random(10),
                        seed,
                        &format!("qext {cfg:?} (ext frames {n_ext})"),
                    );
                    seed += 1;
                }
            }
        }
    }
    assert!(total_ext > 150, "frames with QEXT payloads: {total_ext}");
    // Corrupted extension payloads, and stereo stream decoded to mono.
    let mut cfg = EncCfg::new(2, 1920, 1500, Sig::Clicks);
    cfg.fs = 96000;
    cfg.qext = true;
    let pkts = gen_packets(&cfg, 20, 5);
    assert!(pkts.iter().all(|p| p.1.is_some()));
    let mut rng = Rng::new(3);
    let mut p = Pair::new(96000, 2);
    for (i, (m, e)) in pkts.iter().enumerate() {
        let mut e = e.clone().unwrap();
        if i % 2 == 1 {
            let l = rng.range_i32(0, e.len() as i32) as usize;
            e.truncate(l);
            rng.fill_bytes(&mut e[l / 2..]);
        }
        p.decode(
            Some(m),
            m.len() as i32,
            1920,
            false,
            Some(&e),
            &mut rng,
            "qext corrupt",
        );
    }
    let mut p = Pair::new(96000, 1);
    p.set(CELT_SET_CHANNELS_REQUEST, 2);
    run_stream(&mut p, &pkts, 1920, Loss::Bursts(3), 9, "qext 2->1");
}

// ---------------------------------------------------------------------------------------------
// Custom modes
// ---------------------------------------------------------------------------------------------

#[cfg(feature = "custom-modes")]
#[test]
fn custom_mode_streams() {
    use opusorus::celt::modes::opus_custom_mode_create_custom;
    assert!(c::has_custom());
    let mut seed = 3000u64;
    let mut modes = vec![
        (48000, 960),
        (48000, 480),
        (44100, 512),
        (32000, 320),
        (16000, 160),
        (8000, 80),
        (24000, 240),
        (12000, 256),
    ];
    if cfg!(feature = "qext") {
        modes.push((96000, 1920));
        modes.push((96000, 1024));
    }
    for &(fs, frame) in &modes {
        let mode = opus_custom_mode_create_custom(fs, frame).unwrap();
        let mode: &CeltMode = &mode;
        for &ch in &[1, 2] {
            let mut e = CeltEnc::new_custom(fs, frame, ch).unwrap();
            let mut cd = c::CeltDec::new_custom(fs, frame, ch).unwrap();
            let mut rd = CustomDecoder::opus_custom_decoder_create(mode, ch).unwrap();
            let ctx = format!("custom fs={fs} frame={frame} ch={ch}");
            assert_state_eq(&ctx, &rust_state(&rd), &cd.state());
            let vbr = seed.is_multiple_of(2);
            if vbr {
                assert_eq!(e.ctl(sys::OPUS_SET_VBR_REQUEST, 1), 0);
                assert_eq!(e.ctl(sys::OPUS_SET_BITRATE_REQUEST, 48000 * ch), 0);
            }
            let cu = ch as usize;
            let max_lm = mode.max_lm;
            let nframes = 40;
            let pcm = gen_signal(
                [Sig::Speech, Sig::Music, Sig::Clicks][seed as usize % 3],
                frame as usize * nframes,
                cu,
                fs as u32,
                seed,
            );
            let mut rng = Rng::new(seed);
            let mut pos = 0usize;
            for f in 0..nframes {
                let lm = rng.range_i32(0, max_lm);
                let fsz = mode.short_mdct_size << lm;
                let nbytes = rng.range_i32(8, 200);
                let (ret, out) = e.encode(&pcm[pos * cu..(pos + fsz as usize) * cu], fsz, nbytes);
                pos += fsz as usize;
                assert!(ret > 0, "{ctx}: custom encode {ret}");
                let mut pkt = out[1..1 + ret as usize].to_vec();
                let lost = f % 9 == 7;
                if f % 11 == 10 {
                    rng.fill_bytes(&mut pkt[1..]);
                }
                let data = if lost { None } else { Some(&pkt[..]) };
                let len = pkt.len() as i32;
                let ctx = format!("{ctx} frame {f} lm={lm}");
                match f % 3 {
                    #[cfg(not(feature = "disable-float-api"))]
                    0 => {
                        let mut pc = vec![0f32; frame as usize * cu];
                        let mut pr = pc.clone();
                        let rc = cd.custom_decode_float(data, len, &mut pc, frame);
                        let rr = rd.opus_custom_decode_float(data, len, &mut pr, frame);
                        assert_eq!(code(rr), rc, "{ctx}: ret");
                        assert_bits_eq_f32(&ctx, &pr, &pc);
                    }
                    1 => {
                        let mut pc = vec![0i16; frame as usize * cu];
                        let mut pr = pc.clone();
                        let rc = cd.custom_decode(data, len, &mut pc, frame);
                        let rr = rd.opus_custom_decode(data, len, &mut pr, frame);
                        assert_eq!(code(rr), rc, "{ctx}: ret");
                        assert_slice_eq(&ctx, &pr, &pc);
                    }
                    _ => {
                        let mut pc = vec![0i32; frame as usize * cu];
                        let mut pr = pc.clone();
                        let rc = cd.custom_decode24(data, len, &mut pc, frame);
                        let rr = rd.opus_custom_decode24(data, len, &mut pr, frame);
                        assert_eq!(code(rr), rc, "{ctx}: ret");
                        assert_slice_eq(&ctx, &pr, &pc);
                    }
                }
                assert_state_eq(&ctx, &rust_state(&rd), &cd.state());
            }
            // Signalling errors: invalid TOC, buffer too small.
            for pkt in [
                vec![0x00u8, 1, 2, 3],
                vec![0xFF, 0x40],
                vec![0xFB, 0x41, 0xFF],
                vec![0xE3],
            ] {
                for &fsz in &[frame, mode.short_mdct_size] {
                    #[cfg(not(feature = "disable-float-api"))]
                    {
                        let mut pc = vec![0f32; frame as usize * cu];
                        let mut pr = pc.clone();
                        let rc = cd.custom_decode_float(Some(&pkt), pkt.len() as i32, &mut pc, fsz);
                        let rr =
                            rd.opus_custom_decode_float(Some(&pkt), pkt.len() as i32, &mut pr, fsz);
                        assert_eq!(code(rr), rc, "{ctx}: signalling error {pkt:?}");
                        assert_bits_eq_f32(&ctx, &pr, &pc);
                    }
                    // DISABLE_FLOAT_API: 24-bit output.
                    #[cfg(feature = "disable-float-api")]
                    {
                        let mut pc = vec![0i32; frame as usize * cu];
                        let mut pr = pc.clone();
                        let rc = cd.custom_decode24(Some(&pkt), pkt.len() as i32, &mut pc, fsz);
                        let rr =
                            rd.opus_custom_decode24(Some(&pkt), pkt.len() as i32, &mut pr, fsz);
                        assert_eq!(code(rr), rc, "{ctx}: signalling error {pkt:?}");
                        assert_slice_eq(&ctx, &pr, &pc);
                    }
                    assert_state_eq(&ctx, &rust_state(&rd), &cd.state());
                }
            }
            seed += 1;
        }
    }
}

/// Custom-mode (signalling) packets carrying a QEXT extension in their padding.
#[cfg(all(feature = "custom-modes", feature = "qext"))]
#[test]
fn custom_mode_qext_signalling() {
    use opusorus::celt::modes::opus_custom_mode_create_custom;
    let mut code3 = 0;
    for &(fs, frame) in &[(48000, 960), (96000, 1920)] {
        let mode = opus_custom_mode_create_custom(fs, frame).unwrap();
        let mode: &CeltMode = &mode;
        for &ch in &[1, 2] {
            let mut e = CeltEnc::new_custom(fs, frame, ch).unwrap();
            assert_eq!(e.ctl(sys::OPUS_SET_QEXT_REQUEST, 1), 0);
            let mut cd = c::CeltDec::new_custom(fs, frame, ch).unwrap();
            let mut rd = CustomDecoder::opus_custom_decoder_create(mode, ch).unwrap();
            let cu = ch as usize;
            let pcm = gen_signal(Sig::Music, frame as usize * 12, cu, fs as u32, 11);
            let mut rng = Rng::new(5);
            for f in 0..12 {
                let nbytes = rng.range_i32(300, 1800);
                let (ret, out) = e.encode(
                    &pcm[f * frame as usize * cu..(f + 1) * frame as usize * cu],
                    frame,
                    nbytes,
                );
                assert!(ret > 0);
                let pkt = &out[1..1 + ret as usize];
                #[cfg(not(feature = "disable-float-api"))]
                let mut pc = vec![0f32; frame as usize * cu];
                #[cfg(not(feature = "disable-float-api"))]
                let rc = cd.custom_decode_float(Some(pkt), ret, &mut pc, frame);
                #[cfg(not(feature = "disable-float-api"))]
                let mut pr = pc.clone();
                #[cfg(not(feature = "disable-float-api"))]
                let rr = rd.opus_custom_decode_float(Some(pkt), ret, &mut pr, frame);
                // DISABLE_FLOAT_API: 24-bit output.
                #[cfg(feature = "disable-float-api")]
                let mut pc = vec![0i32; frame as usize * cu];
                #[cfg(feature = "disable-float-api")]
                let rc = cd.custom_decode24(Some(pkt), ret, &mut pc, frame);
                #[cfg(feature = "disable-float-api")]
                let mut pr = pc.clone();
                #[cfg(feature = "disable-float-api")]
                let rr = rd.opus_custom_decode24(Some(pkt), ret, &mut pr, frame);
                code3 += usize::from(pkt[0] & 3 == 3);
                let ctx = format!(
                    "custom qext fs={fs} ch={ch} frame {f} (code3={})",
                    pkt[0] & 3 == 3
                );
                assert_eq!(code(rr), rc, "{ctx}");
                #[cfg(not(feature = "disable-float-api"))]
                assert_bits_eq_f32(&ctx, &pr, &pc);
                #[cfg(feature = "disable-float-api")]
                assert_slice_eq(&ctx, &pr, &pc);
                assert_state_eq(&ctx, &rust_state(&rd), &cd.state());
            }
        }
    }
    assert!(code3 > 20, "code-3 QEXT packets: {code3}");
}

/// Rough speed comparison with the C decoder (run with `--ignored --nocapture`).
#[test]
#[ignore = "timing only"]
fn perf_vs_c() {
    use std::time::Instant;
    let mut cfg = EncCfg::new(2, 960, 1275, Sig::Music);
    cfg.vbr_bitrate = 128000;
    let pkts = gen_packets(&cfg, 500, 1);
    let mut r = CeltDecoder::celt_decoder_init(48000, 2).unwrap();
    r.set_signalling(0);
    let mut cd = c::CeltDec::new(48000, 2).unwrap();
    cd.ctl_set(CELT_SET_SIGNALLING_REQUEST, 0);
    let mut pcm = vec![Res::default(); 1920];
    for _ in 0..3 {
        let t = Instant::now();
        for (m, _) in &pkts {
            cd.decode(Some(m), m.len() as i32, &mut pcm, 960, false, None);
        }
        let tc = t.elapsed();
        let t = Instant::now();
        for (m, _) in &pkts {
            r.celt_decode_with_ec(Some(m), m.len() as i32, &mut pcm, 960, None, false)
                .unwrap();
        }
        let tr = t.elapsed();
        println!(
            "C {tc:?}  Rust {tr:?}  ratio {:.2}",
            tr.as_secs_f64() / tc.as_secs_f64()
        );
    }
}
