#!/usr/bin/env python3
"""Generates crates/opusorus/src/dnn/lossgen_data.rs from the libopus 1.6.1 model data
vendor/libopus/dnn/lossgen_data.c / lossgen_data.h (packet loss generator, --enable-lossgen).

The model data is not vendored in git: run scripts/fetch_dnn_models.sh first. Upstream always
compiles these tables in (opus_demo -sim_loss, lossgen_demo), so they become Rust statics
(PLAN D-027); the element literals are copied verbatim (as `f64` literals converted to
`f32`, the C conversion). The conformance test `lossgen`
compares every array byte for byte with the oracle's `lossgen_arrays`.

Usage: python3 scripts/gen_lossgen_data.py   (from the repository root)
"""

import re
import sys

ROOT = '.'
DATA_C = ROOT + '/vendor/libopus/dnn/lossgen_data.c'
DATA_H = ROOT + '/vendor/libopus/dnn/lossgen_data.h'
OUT = ROOT + '/crates/opusorus/src/dnn/lossgen_data.rs'

TYPES = {'float': ('f32', 'WEIGHT_TYPE_FLOAT', 4), 'opus_int8': ('i8', 'WEIGHT_TYPE_INT8', 1)}


def main():
    try:
        c = open(DATA_C).read()
        h = open(DATA_H).read()
    except OSError as e:
        sys.exit(f'{e}; run scripts/fetch_dnn_models.sh first')
    checkpoint = re.search(r'Auto generated from checkpoint (\S+)', c).group(1)

    # Arrays, in definition order.
    arrays = []
    for m in re.finditer(r'static const (float|opus_int8) (\w+)\[(\d+)\] = \{(.*?)\};', c, re.S):
        ctype, name, n, body = m.group(1), m.group(2), int(m.group(3)), m.group(4)
        vals = [v.strip() for v in body.replace('\n', ' ').split(',') if v.strip()]
        assert len(vals) == n, name
        arrays.append((ctype, name, vals))
    by_name = {a[1]: a for a in arrays}

    # lossgen_arrays order (the #ifdef'd entries that exist).
    table = re.search(r'const WeightArray lossgen_arrays\[\] = \{(.*?)\{NULL', c, re.S).group(1)
    order = [n for n in re.findall(r'\{"(\w+)",', table) if n in by_name]
    assert sorted(order) == sorted(by_name), 'table/array mismatch'

    # init_lossgen.
    init = re.search(r'int init_lossgen\(LossGen \*model,const WeightArray \*arrays\) \{(.*?)return 0;',
                     c, re.S).group(1)
    layers = []
    for m in re.finditer(r'linear_init\(&model->(\w+),arrays,(.*?)\)\) return 1;', init):
        args = [a.strip() for a in m.group(2).split(',')]
        assert len(args) == 9, m.group(0)
        layers.append((m.group(1), args[:7], int(args[7]), int(args[8])))

    defines = re.findall(r'#define (LOSSGEN_\w+) (\d+)', h)
    struct_fields = re.findall(r'LinearLayer (\w+);', h)
    assert struct_fields == [l[0] for l in layers], 'struct/init mismatch'

    o = []
    o.append('//! Port of the generated dnn/lossgen_data.c / lossgen_data.h (libopus 1.6.1 model data,')
    o.append(f'//! checkpoint `{checkpoint}`): the packet loss generator model of `--enable-lossgen`.')
    o.append('//!')
    o.append('//! Upstream always compiles these tables in (they are not part of the DNN weight blob), so')
    o.append('//! they are Rust statics here (PLAN D-027). Generated by `scripts/gen_lossgen_data.py`; the')
    o.append('//! `lossgen` differential test compares every array with the oracle\'s `lossgen_arrays`.')
    o.append('')
    o.append('use alloc::vec::Vec;')
    o.append('')
    o.append('use crate::Result;')
    o.append('use crate::dnn::nnet::{LinearLayer, WEIGHT_TYPE_FLOAT, WEIGHT_TYPE_INT8};')
    o.append('use crate::dnn::parse_lpcnet_weights::{WeightArray, linear_init};')
    o.append('')
    for name, val in defines:
        o.append(f'/// `{name}`.')
        o.append(f'pub const {name}: usize = {val};')
    o.append('')
    for ctype, name, vals in arrays:
        rty, _, _ = TYPES[ctype]
        o.append(f'/// `{name}`.')
        o.append('#[rustfmt::skip]')
        o.append(f'pub static {name.upper()}: [{rty}; {len(vals)}] = [')
        per = 4 if rty == 'f32' else 16
        for i in range(0, len(vals), per):
            chunk = vals[i:i + per]
            if rty == 'f32':
                # C converts the (double) literal to float: decimal -> double -> float, which a
                # direct decimal -> f32 parse can round differently.
                chunk = [v + '_f64 as f32' for v in chunk]
            o.append('    ' + ', '.join(chunk) + ',')
        o.append('];')
        o.append('')
    o.append('/// One compiled-in array: `(name, WEIGHT_TYPE_*, little-endian payload)`.')
    o.append('pub type OwnedWeightArray = (&\'static str, i32, Vec<u8>);')
    o.append('')
    o.append('fn f32_bytes(x: &[f32]) -> Vec<u8> {')
    o.append('    x.iter().flat_map(|v| v.to_le_bytes()).collect()')
    o.append('}')
    o.append('')
    o.append('fn i8_bytes(x: &[i8]) -> Vec<u8> {')
    o.append('    x.iter().map(|&v| v as u8).collect()')
    o.append('}')
    o.append('')
    o.append('/// `lossgen_arrays`: the compiled-in table in upstream order, as the byte payloads the')
    o.append('/// weight-blob parser yields ([`as_weight_arrays`] borrows them as [`WeightArray`]s).')
    o.append('#[must_use]')
    o.append('pub fn lossgen_arrays() -> Vec<OwnedWeightArray> {')
    o.append('    alloc::vec![')
    for name in order:
        ctype = by_name[name][0]
        _, wt, _ = TYPES[ctype]
        conv = 'f32_bytes' if ctype == 'float' else 'i8_bytes'
        o.append(f'        ("{name}", {wt}, {conv}(&{name.upper()})),')
    o.append('    ]')
    o.append('}')
    o.append('')
    o.append('/// Borrows owned arrays as the [`WeightArray`] list `linear_init` binds from.')
    o.append('#[must_use]')
    o.append('pub fn as_weight_arrays(arrays: &[OwnedWeightArray]) -> Vec<WeightArray<\'_>> {')
    o.append('    arrays')
    o.append('        .iter()')
    o.append('        .map(|(name, type_, data)| WeightArray {')
    o.append('            name: name.as_bytes(),')
    o.append('            type_: *type_,')
    o.append('            // The arrays are a few KiB: the size always fits.')
    o.append('            size: data.len() as i32,')
    o.append('            data,')
    o.append('        })')
    o.append('        .collect()')
    o.append('}')
    o.append('')
    o.append('/// `LossGen`: the layers of the loss generator model.')
    o.append('#[derive(Debug, Clone, Default, PartialEq)]')
    o.append('pub struct LossGen {')
    for f in struct_fields:
        o.append(f'    pub {f}: LinearLayer,')
    o.append('}')
    o.append('')
    o.append('/// Port of the generated dnn/lossgen_data.c:init_lossgen (fails with `BadArg` where C returns')
    o.append('/// 1).')
    o.append('pub fn init_lossgen(arrays: &[WeightArray<\'_>]) -> Result<LossGen> {')
    o.append('    Ok(LossGen {')
    for f, names, nin, nout in layers:
        o.append(f'        {f}: linear_init(')
        o.append('            arrays,')
        for a in names:
            o.append('            None,' if a == 'NULL' else f'            Some({a}),')
        o.append(f'            {nin},')
        o.append(f'            {nout},')
        o.append('        )?,')
    o.append('    })')
    o.append('}')
    open(OUT, 'w').write('\n'.join(o) + '\n')
    print(f'wrote {OUT}: {len(arrays)} arrays, {len(layers)} layers')


if __name__ == '__main__':
    main()
